### ISSUE TITLE
Trained model for CIFAR 100

### ISSUE THREAD

**Issue by vidit98** [kibok90/iccv2019-inc#1]
I really liked the proposed method. Could you please share the weights of the model trained on CIFAR-100.

**Comment by kibok90** [comment]
Hi @vidit98,

Here is the zip file containing all model files and performance logs of GD+ext on CIFAR-100.
https://drive.google.com/open?id=1O8EJxw46_6QrReaXfQD5DhvPtAOBX8h0

With this, you can replicate the following performances in Table 1:

task size = 5
ACC: 66.3 ± 1.2
FGT: 9.8 ± 0.3

task size = 10
ACC: 68.1 ± 1.1
FGT: 7.7 ± 0.3

task size = 20
ACC: 68.9 ± 1.0
FGT: 5.5 ± 0.4

**Comment by vidit98** [comment]
Thanks a lot!
