### ISSUE TITLE
How to proceed if we use our own dataset?

### ISSUE THREAD

**Issue by Vidushi1107** [kibok90/iccv2019-inc#3]
I saw that for cifar-100, a lot of custom code is written. I have already went through another issue where the author recommend to use H5dataset part of code. But still I have doubts, is there a specific manner in which the data have to be used ?

Will I have to write that custom code for my dataset also ? Any clue or directions will be very helpful.

Also, I am asking for main Dataset input, not about unlabeled dataset.

**Comment by kibok90** [comment]
If you want to use your own dataset without modifying the code, you can simply convert your dataset to match the format with the imagenet dataset, which is loaded using the H5Dataset class.

You can find the link to download it in the instruction:
  - Download [[train (1.5GB)](https://drive.google.com/open?id=1FyaXjtCPg1_33i30--oORtspzFwSAa30)], [[test (0.3GB)](https://drive.google.com/open?id=18vYTxXpVB0lMrMitw3fVm2abGhWW37sN)] and place them in `data/imagenet/`.
  - Download [[here (20 files; each takes 3GB)](https://drive.google.com/drive/folders/194-V0tSOA82mTqFmDzEa83wA6B56Itr2)] and place them in `data/imagenet/`.
    - Download [[0 (3GB)](https://drive.google.com/open?id=1eIw7kVvMM1gzzdq_qx2qaViYF2Qx4mTb)] only, if you use `--ex-static` for training.


Below might also be useful:

creating an H5 file:
https://github.com/kibok90/iccv2019-inc/blob/master/sample_imagenet.py#L211-L213

loading an H5 file:
https://github.com/kibok90/iccv2019-inc/blob/master/datasets/inc_ext.py#L445-L447
